# Generated by Django 2.2 on 2020-11-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('historia', models.CharField(max_length=50)),
                ('titulos', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('posicion', models.CharField(blank=True, choices=[('Delantero', 'Delantero'), ('Mediocampo', 'Mediocampo'), ('Defenzor', 'Defenzor'), ('Arquero', 'Arquero')], max_length=50)),
                ('edad', models.IntegerField()),
                ('valor', models.IntegerField(default=0)),
                ('mediaritmo', models.IntegerField(default=0)),
                ('mediapases', models.IntegerField(default=0)),
                ('mediatiros', models.IntegerField(default=0)),
                ('mediaregates', models.IntegerField(default=0)),
                ('mediadefenza', models.IntegerField(default=0)),
                ('mediafisico', models.IntegerField(default=0)),
                ('club', models.ForeignKey(max_length=50, on_delete='on_delete', to='core.Club')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.CharField(default=0, max_length=50)),
                ('email', models.CharField(default='...', max_length=50)),
                ('dinero', models.IntegerField(default=1000)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Propios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jugador', models.ForeignKey(default=1, max_length=50, on_delete='on_delete', to='core.Jugador')),
                ('usuario', models.ForeignKey(default=1, max_length=50, on_delete='on_delete', to='core.Usuario')),
            ],
            options={
                'verbose_name': 'Propio',
                'verbose_name_plural': 'propios',
            },
        ),
        migrations.CreateModel(
            name='DT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historia', models.CharField(default='NULL', max_length=60)),
                ('nombre', models.CharField(max_length=50)),
                ('valor', models.CharField(default='1', max_length=50)),
                ('edad', models.CharField(default='1', max_length=50)),
                ('club', models.ForeignKey(max_length=50, on_delete='on_delete', to='core.Club')),
            ],
            options={
                'verbose_name': 'Director Tecnico',
                'verbose_name_plural': 'Directores Tecnicos',
            },
        ),
    ]
