# Generated by Django 2.2 on 2020-12-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='precio',
            field=models.FloatField(default=0),
        ),
    ]
