# Generated by Django 2.2 on 2020-11-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nickname',
            field=models.CharField(default='Aa', max_length=50),
        ),
    ]
