# Generated by Django 2.2 on 2020-11-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nickname',
            field=models.CharField(max_length=50),
        ),
    ]
