# Generated by Django 2.2 on 2020-11-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201126_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinero',
            name='cantidad',
            field=models.IntegerField(default=1000),
        ),
    ]
