# Generated by Django 2.2 on 2020-11-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dinero_cantidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dinero',
            options={'verbose_name': 'Dinero', 'verbose_name_plural': 'Dinero'},
        ),
        migrations.AddField(
            model_name='dinero',
            name='dueño',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
