# Generated by Django 2.2 on 2020-11-27 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201126_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=150)),
                ('img', models.ImageField(upload_to=models.CharField(max_length=150))),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epigrafe', models.CharField(max_length=100)),
                ('titular', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=100)),
                ('entradilla', models.CharField(max_length=300)),
                ('cuerpo', models.CharField(max_length=2000)),
                ('imagen', models.ForeignKey(on_delete='on_delete', to='core.Imagen')),
            ],
        ),
    ]
