# Generated by Django 2.2 on 2020-11-27 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_imagen_noticia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='img',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='link',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='imagen',
        ),
    ]
