# Generated by Django 2.2 on 2020-11-27 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201127_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('jugador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Jugador')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('core.jugador',),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dinero', models.IntegerField(default=1000)),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.DeleteModel(
            name='Dinero',
        ),
        migrations.RenameField(
            model_name='club',
            old_name='nombre',
            new_name='club',
        ),
        migrations.AddField(
            model_name='jugador',
            name='media',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='edad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
